// Dữ liệu tỉnh/thành phố + xã/phường (không quận/huyện)
const LOCATIONS = {
    'Hà Nội': ['Phường Nguyễn Trung Trực', 'Phường Cống Vị', 'Phường Liễu Giai', 'Phường Ngọc Khánh', 'Phường Quán Thánh', 'Phường Kham Thiên', 'Phường Phúc Tân', 'Phường Trúc Bạch', 'Phường Hàng Bài', 'Phường Hàng Gai', 'Phường Hàng Mã', 'Phường Tân Bình', 'Phường Tây Hồ', 'Phường Đống Đa', 'Phường Bà Triệu', 'Phường Hàng Bột', 'Phường Vĩnh Tuy', 'Phường Khâm Thiên', 'Phường Quỳnh Lôi', 'Phường Thanh Nhàn', 'Phường Kim Liên', 'Phường Quốc Tử Giám', 'Phường Trần Phú', 'Phường Láng Thượng', 'Phường Láng Hạ', 'Phường Quảng An', 'Phường Tứ Liên', 'Phường Nhật Tân', 'Phường Thụ Khê', 'Phường Ô Cho Dừa', 'Phường Dịch Vọng Hậu', 'Phường Dịch Vọng', 'Phường Trung Hòa', 'Phường Yên Hòa', 'Phường Cầu Giấy', 'Phường Quan Hoa', 'Phường Mai Dịch', 'Phường Thanh Xuân Nam', 'Phường Thanh Xuân Bắc', 'Phường Thanh Xuân Trung', 'Phường Việt Hùng', 'Phường Gia Thụy', 'Phường Giang Biên', 'Phường Ngô Quyền', 'Phường Hoàng Văn Thụ', 'Phường Hoàng Liệt', 'Phường Tây Thạnh', 'Phường Đại Kim', 'Phường Hạ Đình', 'Phường Thạnh Trì', 'Phường Phú Sơn', 'Phường Phú Minh'],
    'TP. Hồ Chí Minh': ['Phường Bến Nghé', 'Phường Bến Thành', 'Phường Cô Giang', 'Phường Đa Kao', 'Phường Nguyễn Hữu Cảnh', 'Phường Tân Định', 'Phường An Khánh', 'Phường An Lợi Đông', 'Phường Thạnh Mỹ Lợi', 'Phường Thủ Thiêm', 'Phường Bình Trưng Đông', 'Phường Bình Trưng Tây', 'Phường 1', 'Phường 2', 'Phường 3', 'Phường 4', 'Phường 5', 'Phường 6', 'Phường 7', 'Phường 8', 'Phường 9', 'Phường 10', 'Phường 11', 'Phường 12', 'Phường 13', 'Phường 14', 'Phường 15', 'Phường 16', 'Phường An Phú', 'Phường Tân Phú', 'Phường Long Bình', 'Phường Long Thạnh Mỹ', 'Phường Trường Thạnh'],
    'Đà Nẵng': ['Phường Hải Châu', 'Phường Thanh Khê', 'Phường Chính Gián', 'Phường Tân Chính', 'Phường Thạch Thang', 'Phường Xuân Phương', 'Phường Sơn Trà', 'Phường Khuê Trung', 'Phường An Hải Bắc', 'Phường An Hải Tây', 'Phường Mân Thái', 'Phường Nại Hiên Tây', 'Phường Nại Hiên Đông', 'Phường Mỹ An', 'Phường Hòa Khánh Bắc', 'Phường Hòa Khánh Nam', 'Phường Hòa Hiệp Bắc', 'Phường Hòa Hiệp Nam', 'Phường Hòa Cương Bắc', 'Phường Hòa Cương Nam'],
    'Hải Phòng': ['Phường Hiệp Hòa', 'Phường Máy Chai', 'Phường Phạm Hùng', 'Phường Cầu Tre', 'Phường Vĩnh Bảo', 'Phường Diêm Điếu', 'Phường Chợ Dầu', 'Phường Gia Thụy', 'Phường Thành Công', 'Phường Tràng Cát', 'Phường Tân Sơn', 'Phường Quán Toan', 'Phường Hà Kỳ', 'Phường Kiến An', 'Phường Hải Tân', 'Phường Hùng Vương'],
    'Cần Thơ': ['Phường An Hòa', 'Phường An Khánh', 'Phường An Phú', 'Phường Cái Khế', 'Phường Hưng Lợi', 'Phường Ninh Kiều', 'Phường Xuân Phú', 'Phường Châu Văn Liêm', 'Phường Long Hữu', 'Phường Ô Môn', 'Phường Thới An', 'Phường Thới Bình', 'Phường Bình Thủy', 'Phường Phong Điền', 'Phường Trà Nơn', 'Phường Trà An', 'Phường Ưu Nhu'],
    'Hà Giang': ['Phường Hà Giang', 'Phường Quang Trung', 'Phường Vị Xuyên'],
    'Cao Bằng': ['Thị xã Cao Bằng', 'Huyện Thái Nguyên'],
    'Bắc Kạn': ['Thành phố Bắc Kạn'],
    'Tuyên Quang': ['Thành phố Tuyên Quang'],
    'Lào Cai': ['Thành phố Lào Cai', 'Thị trấn Sapa'],
    'Điện Biên': ['Thành phố Điện Biên Phủ'],
    'Lai Châu': ['Thành phố Lai Châu'],
    'Sơn La': ['Thành phố Sơn La'],
    'Yên Bái': ['Thành phố Yên Bái'],
    'Hòa Bình': ['Thành phố Hòa Bình'],
    'Hưng Yên': ['Thành phố Hưng Yên'],
    'Thái Bình': ['Thành phố Thái Bình'],
    'Hà Nam': ['Thành phố Phủ Lý'],
    'Nam Định': ['Thành phố Nam Định'],
    'Ninh Bình': ['Thành phố Ninh Bình'],
    'Thanh Hóa': ['Thành phố Thanh Hóa'],
    'Nghệ An': ['Thành phố Vinh'],
    'Hà Tĩnh': ['Thành phố Hà Tĩnh'],
    'Quảng Bình': ['Thành phố Đồng Hới'],
    'Quảng Trị': ['Thành phố Đông Hà'],
    'Thừa Thiên - Huế': ['Thành phố Huế'],
    'Quảng Nam': ['Thành phố Hội An', 'Thành phố Tam Kỳ'],
    'Quảng Ngãi': ['Thành phố Quảng Ngãi'],
    'Bình Định': ['Thành phố Quy Nhơn'],
    'Phú Yên': ['Thành phố Tuy Hòa'],
    'Khánh Hòa': ['Thành phố Nha Trang'],
    'Ninh Thuận': ['Thành phố Phan Rang - Tháp Chàm'],
    'Bình Thuận': ['Thành phố Phan Thiết'],
    'Đắk Lắk': ['Thành phố Buôn Ma Thuột'],
    'Đắk Nông': ['Thành phố Gia Nghĩa'],
    'Gia Lai': ['Thành phố Pleiku'],
    'Kon Tum': ['Thành phố Kon Tum'],
    'Lâm Đồng': ['Thành phố Đà Lạt'],
    'Bình Dương': ['Thành phố Thủ Dầu Một'],
    'Tây Ninh': ['Thành phố Tây Ninh'],
    'Bình Phước': ['Thành phố Đồng Xoài'],
    'Long An': ['Thành phố Tân An'],
    'Tiền Giang': ['Thành phố Mỹ Tho'],
    'Bến Tre': ['Thành phố Bến Tre'],
    'Vĩnh Long': ['Thành phố Vĩnh Long'],
    'Đồng Tháp': ['Thành phố Cao Lãnh'],
    'An Giang': ['Thành phố Long Xuyên'],
    'Kiên Giang': ['Thành phố Rạch Giá'],
    'Hậu Giang': ['Thành phố Vị Thanh'],
    'Sóc Trăng': ['Thành phố Sóc Trăng'],
    'Bạc Liêu': ['Thành phố Bạc Liêu'],
    'Cà Mau': ['Thành phố Cà Mau'],
};

export default LOCATIONS;
